### ISSUE TITLE
build|ark.py raises IndentationError

### ISSUE THREAD

**Issue by JapanYoshi** [hmxmilohax/rock-band-blitz-deluxe#6]
When I run build_ps3.bat, the following error prevents it from completing:

```
Traceback (most recent call last):
  File "C:\Users\Haley\Downloads\rock-band-blitz-deluxe\windows_bats\../user_scripts/build_rpcs3.py", line 8, in <module>
    from build_ark import build_patch_ark
  File "C:\Users\Haley\Downloads\rock-band-blitz-deluxe\user_scripts\../dependencies/dev_scripts\build_ark.py", line 71
    pull the latest changes from the Rock Band Blitz Deluxe repo if necessary
IndentationError: unexpected indent
```

**Comment by JapanYoshi** [comment]
The affected line is: https://github.com/hmxmilohax/rock-band-blitz-deluxe/blob/e4929a666a5b77674339913db1aca8df2724b292/dependencies/dev_scripts/build_ark.py#L71

I suspect that this line was meant to be a comment, but the # was erroneously erased. The following line is awkwardly indented, too. Commenting out line 71 and removing the leading space in line 72 made it run!
